mdbc-server throws exception
This happens when the TablesConfiguration is done.

It's apparently caused because music jar was compiled with
netty 4.1, but the version present at runtime is 4.0.

The solution I propose is to add an explicit dependency in
mdbc for netty 4.1, which should override the 4.0 version
pulled in by cassandra.

Exception (java.lang.AbstractMethodError) encountered during startup: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/util/conc
urrent/EventExecutor;
java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;

Change-Id: Ie658ce4a7621eb2a0d2417d35e0fd2bd96565c8c
Issue-ID: MUSIC-271
Signed-off-by: Rob Daugherty <rd472p@att.com>